cabal-version:      3.0
name:               clover
version:            0.1.0.0
synopsis:           Design your own awesome graphical MPD client
description:        Design your own awesome graphical MPD client
                    .
                    <https://github.com/breitnw/clover#readme>
license:            GPL-3.0-only
license-file:       LICENSE
author:             Nick Breitling
maintainer:         Nick Breitling <breitling.nw@gmail.com>
copyright:          (c) 2026 Nick Breitling
category:           Graphics, Sound
build-type:         Simple

extra-doc-files:    CHANGELOG.md

homepage:           https://github.com/breitnw/clover#readme
bug-reports:        https://github.com/breitnw/clover/issues

source-repository head
  type:     git
  location: https://github.com/breitnw/libmpd-effectful

common warnings
    ghc-options: -Wall

common language
    default-language: Haskell2010
    default-extensions:
        ImportQualifiedPost
        FlexibleContexts
        TypeApplications
        GADTs
        LambdaCase
        TypeFamilies
        TypeOperators
        DataKinds
        ConstraintKinds
        ScopedTypeVariables

library
    import:           warnings, language
    exposed:          True
    default-language: Haskell2010
    hs-source-dirs:   src

    build-depends: 
      base              >=4.16 && <5,
      filepath          >=1    && <2,
      text             ^>=2.1.4,
      bytestring       ^>=0.12.2,
      containers       ^>=0.8,
      sdl3             ^>=0.1,
      bitmap           ^>=0.0.2,
      stb-image        ^>=0.2.1,
      effectful        ^>=2.6.1,
      effectful-th     ^>=1.0.0.4,
      libmpd-effectful ^>=0.1

    exposed-modules: 
      Clover.App,

      -- Effects
      Effectful.MusicPlayer,
      Effectful.MusicPlayer.Handler.MPD,
      Effectful.ImageLoader,
      Effectful.Logger,
      Effectful.Logger.Handler.SDL,
      Effectful.Renderer,
      Effectful.Renderer.Handler.SDL,
      Effectful.Fail.Handler.Log,

    other-modules:
      -- Clover
      Clover.Music.Thread,
      Clover.Graphics.Thread,
      Clover.Graphics.Theme,
      Clover.Graphics.Types,
      Clover.Shared,

      -- Utils
      Util,
      
      -- Effects
      Effectful.MusicPlayer.Effect,
      Effectful.MusicPlayer.Types,

      Effectful.ImageLoader.Effect,
      Effectful.ImageLoader.Types,

      Effectful.Logger.Effect,

      Effectful.Renderer.Effect,
      Effectful.Renderer.Types,
      Effectful.Renderer.Managed,

executable clover
    import:           warnings, language
    default-language: Haskell2010
    main-is:          Main.hs
    hs-source-dirs:   run

    build-depends:
      base >=4.16 && <5,
      clover

executable logger
    import:           warnings, language
    default-language: Haskell2010
    main-is:          Logger.hs
    hs-source-dirs:   examples

    build-depends:
      base >=4.16 && <5,
      clover
