cabal-version:      3.0
name:               clover
version:            0.1.0.0
synopsis:           Design your own awesome graphical MPD client
description:        Design your own awesome graphical MPD client
                    .
                    <https://github.com/breitnw/clover#readme>
license:            GPL-3.0-only
license-file:       LICENSE
author:             Nick Breitling
maintainer:         Nick Breitling <breitling.nw@gmail.com>
copyright:          (c) 2026 Nick Breitling
category:           Graphics
build-type:         Simple

extra-doc-files:    CHANGELOG.md

common warnings
    ghc-options: -Wall

library
    import:           warnings
    exposed:          False
    default-language: Haskell2010
    hs-source-dirs:   src

    build-depends: 
      base >=4.16 && <5,
      mtl,
      bytestring,
      containers,
      bitmap,
      stb-image ^>= 0.2.1,
      sdl3 >= 0.1.0.0,
      libmpd ^>=0.10.0.0

    exposed-modules: 
      Clover.App

    other-modules:
      Clover.Backend
      Clover.Backend.Class
      Clover.Backend.Data
      Clover.Backend.Error
      Clover.Backend.Impl.MPD
      Clover.Backend.Util.Cache

executable clover
    import:           warnings
    default-language: Haskell2010
    main-is:          Main.hs
    hs-source-dirs:   run

    build-depends:
      base >=4.16 && <5,
      clover
